version: "3.9"
services:
  greeter-projection:
    image: cassandra
    ports:
      - "9042:9042"
      - "7000:7000"

  event-broker:
    image: apachepulsar/pulsar
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: "bin/pulsar standalone"
